# Generated by Django 5.2.4 on 2025-09-03 16:36

import Api_banco.webScraping.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='scrapingList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codScraping', models.CharField(default='Scraping', max_length=100)),
                ('timenow', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='exchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('compra', models.CharField(max_length=100)),
                ('venta', models.CharField(max_length=100)),
                ('scrapingID', models.ForeignKey(blank=True, default=Api_banco.webScraping.models.get_default_scraping, null=True, on_delete=django.db.models.deletion.CASCADE, to='webScraping.scrapinglist')),
            ],
        ),
    ]
